In [26]:
import numpy as np

In [27]:
a = np.array([2, 33, 4], dtype=np.float32)
print(a)
print(a.dtype)

[  2.  33.   4.]
float32


In [28]:
a = np.array([[1, 2, 3], 
             [2, 3, 4]], dtype=np.float32)
print(a)

[[ 1.  2.  3.]
 [ 2.  3.  4.]]


In [37]:
a = np.zeros([2, 2, 3])
print(a)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [38]:
a = np.ones([2, 2, 1])
print(a)

[[[ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]]]


In [39]:
a = np.empty((2, 3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [45]:
a = np.arange(12).reshape([3, 4])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
a = np.linspace(1, 10, 20).reshape((4, 5))
print(a)

[[  1.           1.47368421   1.94736842   2.42105263   2.89473684]
 [  3.36842105   3.84210526   4.31578947   4.78947368   5.26315789]
 [  5.73684211   6.21052632   6.68421053   7.15789474   7.63157895]
 [  8.10526316   8.57894737   9.05263158   9.52631579  10.        ]]
