In [1]:
import numpy as np

In [3]:
a = np.array([10, 23, 31, 41])
b = np.arange(4)
print(a, b)


[10 23 31 41] [0 1 2 3]


In [4]:
c = a - b
print(c)

[10 22 29 38]


In [6]:
print(a**5)

[   100000   6436343  28629151 115856201]


In [8]:
print(b*np.sin(a))

[-0.         -0.8462204  -0.80807529 -0.47586801]


In [12]:
print(b == 3)

[False False False  True]


In [25]:
# matrix
a = np.array([[11, 21, 31], [12, 13, 14]])
b = np.arange(6).reshape([3, 2])
c = np.matmul(a, b)
d = np.dot(a, b)
e = a.dot(b)
# print(a)
# print(b)
print(c)
print(d)
print(e)

[[166 229]
 [ 82 121]]
[[166 229]
 [ 82 121]]
[[166 229]
 [ 82 121]]


In [32]:
a = np.random.random((2, 3))
print(a)

print(np.sum(a))
print(np.sum(a, axis=1))
print(np.min(a))
print(np.max(a))

[[ 0.62513474  0.55160229  0.51376629]
 [ 0.35723034  0.67521952  0.69987248]]
3.42282565466
[ 1.69050332  1.73232234]
0.357230336185
0.699872483512


In [41]:
# computation 2
A = np.arange(2, 14).reshape([3, 4])
print(A)
print(A.mean())
print(np.average(A))
print(np.cumsum(A))
print(A.T)
print(np.transpose(A))
print(np.clip(A, 2, 6))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[2 3 4 5]
 [6 6 6 6]
 [6 6 6 6]]
