In [1]:
import numpy as np

In [3]:
A = np.arange(3, 15)
print(A)
print(A[2])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
5


In [12]:
A = np.arange(3, 15).reshape([3, 4])
# print(A)
print(A[1,1])
print(A[1][1])
print(A[1, 1:3])

8
8
[8 9]


In [16]:
for col in A.T:
    print(col)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [18]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
