In [1]:
import numpy as np

In [3]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

# veritcal stack
print(np.vstack((A, B))) 
C = np.vstack((A, B))
print(A.shape)
print(C.shape)

[[1 1 1]
 [2 2 2]]
(3,)
(2, 3)


In [5]:
D = np.hstack((A, B))
print(D)
print(D.shape)

[1 1 1 2 2 2]
(6,)


In [9]:
print(A[np.newaxis, :])
print(A[np.newaxis, :].shape)
print(A[:, np.newaxis])
print(A[:, np.newaxis].shape)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [19]:
A = np.arange(0, 3).reshape((1, 3))
B = np.arange(1, 4).reshape((1, 3))

In [20]:
E = np.concatenate((A, B, A, A))
print(E)
F = np.concatenate((A, B, A, A), axis = 1)
print(F)

[[0 1 2]
 [1 2 3]
 [0 1 2]
 [0 1 2]]
[[0 1 2 1 2 3 0 1 2 0 1 2]]
