In [1]:
import numpy as np

In [2]:
A = np.arange(4)
print(A)

[0 1 2 3]


In [7]:
B = A
C = A
D = B

In [8]:
A[0] = 11
print(A)

[11  1  2  3]


In [11]:
# print(B)
B is A

True

In [12]:
print(C)

[11  1  2  3]


In [13]:
print(D)

[11  1  2  3]


In [15]:
D[1:3] = [22, 33]

In [17]:
print(A, B, C, D)

[11 22 33  3] [11 22 33  3] [11 22 33  3] [11 22 33  3]


In [18]:
# deep copy
B = A.copy()

In [19]:
print(B)

[11 22 33  3]


In [21]:
A[2] = 10000
print(A, B)

[   11    22 10000     3] [11 22 33  3]
